{{ if .Values.policies.checkDeprecatedApis.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-deprecated-apis
spec:
  validationFailureAction: {{ .Values.policies.checkDeprecatedApis.validationFailureAction }}
  rules:
  - name: validate-v1-22-removals
    match:
      resources:
        kinds:
        - admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration
        - admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration
        - apiextensions.k8s.io/v1beta1/CustomResourceDefinition
        - apiregistration.k8s.io/v1beta1/APIService
        - authentication.k8s.io/v1beta1/TokenReview
        - authorization.k8s.io/v1beta1/SubjectAccessReview
        - authorization.k8s.io/v1beta1/LocalSubjectAccessReview
        - authorization.k8s.io/v1beta1/SelfSubjectAccessReview 
        - certificates.k8s.io/v1beta1/CertificateSigningRequest
        - coordination.k8s.io/v1beta1/Lease
        - extensions/v1beta1/Ingress
        - networking.k8s.io/v1beta1/Ingress
        - networking.k8s.io/v1beta1/IngressClass
        - rbac.authorization.k8s.io/v1beta1/ClusterRole
        - rbac.authorization.k8s.io/v1beta1/ClusterRoleBinding
        - rbac.authorization.k8s.io/v1beta1/Role
        - rbac.authorization.k8s.io/v1beta1/RoleBinding
        - scheduling.k8s.io/v1beta1/PriorityClass
        - storage.k8s.io/v1beta1/CSIDriver
        - storage.k8s.io/v1beta1/CSINode
        #- storage.k8s.io/v1beta1/StorageClass
        - storage.k8s.io/v1beta1/VolumeAttachment
    {{- if or .Values.policies.checkDeprecatedApis.excludeSystemNamespaces  .Values.policies.checkDeprecatedApis.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.checkDeprecatedApis.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        {{- range .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        {{ `"{{ request.object.apiVersion }}/{{ request.object.kind }}"` }} is deprecated and will be removed in v1.22. 
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/        
      deny: {}
  - name: validate-v1-25-removals
    match:
      resources:
        kinds:
        - batch/v1beta1/CronJob
        - discovery.k8s.io/v1beta1/EndpointSlice
        - events.k8s.io/v1beta1/Event
        - policy/v1beta1/PodDisruptionBudget
        - policy/v1beta1/PodSecurityPolicy
        - node.k8s.io/v1beta1/RuntimeClass
    {{- if or .Values.policies.checkDeprecatedApis.excludeSystemNamespaces  .Values.policies.checkDeprecatedApis.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.checkDeprecatedApis.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        {{- range .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        {{ `"{{ request.object.apiVersion }}/{{ request.object.kind }}"` }} is deprecated and will be removed in v1.25. 
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/        
      deny: {}
{{ end }}      