{{ if .Values.policies.requireReadOnlyRootFileSystem.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-read-only-root-filesystem
  annotations:
    policies.kyverno.io/description: >-
      A read-only root file system helps to enforce an immutable infrastructure strategy; 
      the container only needs to write on the mounted volume that persists the state. 
      An immutable root filesystem can also prevent malicious binaries from writing to the 
      host system.
    pod-policies.kyverno.io/autogen-controllers: none       
spec:
  validationFailureAction: {{ .Values.policies.requireReadOnlyRootFileSystem.validationFailureAction }}
  background: {{ .Values.policies.requireReadOnlyRootFileSystem.background }}
  rules:
  - name: validate-readOnlyRootFilesystem
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.requireReadOnlyRootFileSystem.excludeSystemNamespaces  .Values.policies.requireReadOnlyRootFileSystem.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.requireReadOnlyRootFileSystem.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.requireReadOnlyRootFileSystem.excludedNamespaces }}
        {{- range .Values.policies.requireReadOnlyRootFileSystem.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: "Root filesystem must be read-only."
      pattern:
        spec:
          containers:
          - securityContext:
              readOnlyRootFilesystem: true
{{ end }}
