{{ if .Values.policies.requireRunAsNonRoot.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: {{ .Values.policies.requireRunAsNonRoot.validationFailureAction }}
  background: {{ .Values.policies.requireRunAsNonRoot.background }}
  rules:
  - name: check-containers
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.requireRunAsNonRoot.excludeSystemNamespaces  .Values.policies.requireRunAsNonRoot.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.requireRunAsNonRoot.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.requireRunAsNonRoot.excludedNamespaces }}
        {{- range .Values.policies.requireRunAsNonRoot.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        Running as root is not allowed. The fields spec.securityContext.runAsNonRoot,
        spec.containers[*].securityContext.runAsNonRoot, and
        spec.initContainers[*].securityContext.runAsNonRoot must be `true`.        
      anyPattern:
      - spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - =(securityContext):
              =(runAsNonRoot): true
          =(initContainers):
          - =(securityContext):
              =(runAsNonRoot): true              
      - spec:
          containers:
          - securityContext:
              runAsNonRoot: true
          =(initContainers):
          - securityContext:
              runAsNonRoot: true
{{ end }}
