{{ if .Values.policies.restrictSelinux.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-selinux
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none                       
spec:
  validationFailureAction: {{ .Values.policies.restrictSelinux.validationFailureAction }}
  background: {{ .Values.policies.restrictSelinux.background }}
  rules:
  - name: seLinux
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.restrictSelinux.excludeSystemNamespaces  .Values.policies.restrictSelinux.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.restrictSelinux.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.restrictSelinux.excludedNamespaces }}
        {{- range .Values.policies.restrictSelinux.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        Setting custom SELinux options is disallowed. The fields
        spec.securityContext.seLinuxOptions, spec.containers[*].securityContext.seLinuxOptions,
        and spec.initContainers[*].securityContext.seLinuxOptions must be empty.
      pattern:
        spec:
          =(securityContext):
            X(seLinuxOptions): "null"
          =(initContainers):
          - =(securityContext):
              X(seLinuxOptions): "null"
          containers:
          - =(securityContext):
              X(seLinuxOptions): "null"
{{ end }}