{{ if .Values.policies.restrictCustomRuntimes.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-custom-runtime
  annotations:
spec:
  validationFailureAction: {{ .Values.policies.restrictCustomRuntimes.validationFailureAction }}
  background: {{ .Values.policies.restrictCustomRuntimes.background }}
  rules:
  - name: restrict-seccomp
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.restrictCustomRuntimes.excludeSystemNamespaces  .Values.policies.restrictCustomRuntimes.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.restrictCustomRuntimes.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.restrictCustomRuntimes.excludedNamespaces }}
        {{- range .Values.policies.restrictCustomRuntimes.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        Use of custom Seccomp profiles is disallowed. The fields
        spec.securityContext.seccompProfile.type,
        spec.containers[*].securityContext.seccompProfile.type, and
        spec.initContainers[*].securityContext.seccompProfile.type
        must be set to `RuntimeDefault` or `Localhost`.        
      anyPattern:
      - spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault | Localhost | windows-2004 | windows-2019"
      - spec:
          containers:
          - securityContext:
              seccompProfile:
                type: "RuntimeDefault | Localhost | windows-2004 | windows-2019"
  - name: restrict-seccomp-initcontainers
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.restrictCustomRuntimes.excludeSystemNamespaces  .Values.policies.restrictCustomRuntimes.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.restrictCustomRuntimes.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.restrictCustomRuntimes.excludedNamespaces }}
        {{- range .Values.policies.restrictCustomRuntimes.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        Use of custom Seccomp profiles is disallowed. The fields
        spec.securityContext.seccompProfile.type,
        spec.containers[*].securityContext.seccompProfile.type, and
        spec.initContainers[*].securityContext.seccompProfile.type
        must be set to `RuntimeDefault` or `Localhost`.        
      anyPattern:
      - spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault | Localhost | windows-2004 | windows-2019"
      - spec:
          =(initContainers):
          - securityContext:
              seccompProfile:
                type: "RuntimeDefault | Localhost | windows-2004 | windows-2019"             
{{ end }}