{{ if .Values.policies.restrictHostPorts.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-host-ports
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: {{ .Values.policies.restrictHostPorts.validationFailureAction }}
  background: {{ .Values.policies.restrictHostPorts.background }}
  rules:
  - name: host-ports
    match:
      resources:
        kinds:
        - Pod
    {{- if or .Values.policies.restrictHostPorts.excludeSystemNamespaces  .Values.policies.restrictHostPorts.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.restrictHostPorts.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.restrictHostPorts.excludedNamespaces }}
        {{- range .Values.policies.restrictHostPorts.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}              
    validate:
      message: >-
        Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
        and spec.initContainers[*].ports[*].hostPort must be empty.
      pattern:
        spec:
          =(initContainers):
          - =(ports):
              - X(hostPort): 0
          containers:
          - =(ports):
              - X(hostPort): 0
{{ end }}