{{ if .Values.policies.assignTechnicalLabel.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: assign-technical-label
spec:
  background: {{ .Values.policies.assignTechnicalLabel.background }}
  rules: 
  - name: "assign-label"
    match:
      resources:
        kinds:
        - Namespace
        #name: kyverno-dev # Added temporary for development purposes
    preconditions:
      all:
      - key: {{ `"{{serviceAccountName}}"` }}
        operator: In
        value:
        {{- range .Values.policies.assignTechnicalLabel.matchingServiceAccountNames }}
        - {{ . }}
        {{- end }}
      - key: {{ `"{{serviceAccountNamespace}}"` }}
        operator: In
        value:
        {{- range .Values.policies.assignTechnicalLabel.matchingServiceAccountNamespaces }}
        - {{ . }}
        {{- end }}                       
    {{- if or .Values.policies.assignTechnicalLabel.excludeSystemNamespaces  .Values.policies.assignTechnicalLabel.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.assignTechnicalLabel.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.assignTechnicalLabel.excludedNamespaces }}
        {{- range .Values.policies.assignTechnicalLabel.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            {{- with .Values.policies.assignTechnicalLabel.labels }}
              {{- toYaml . | nindent 12 -}}
            {{- end -}}        
{{ end }}